name: Run RocketMQ Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: [26]
        os: [ubuntu-latest]
        rebar3:
          - 3.24.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.31.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          rebar3-version: ${{ matrix.rebar3 }}
      - run: rebar3 compile
      - run: rebar3 dialyzer

      - name: Start RocketMQ with Docker Compose
        run: |
          docker-compose -f .ci/rocketmq.yml down
          docker-compose -f .ci/rocketmq.yml up -d
        env:
          TAG: 5.3.1

      - name: Run tests
        run: |
          rebar3 eunit
          rebar3 ct -v -c --name 'test@127.0.0.1' -v --readable=true
      - name: Get container logs on failure
        if: failure()
        run: |
          echo "============== rmqbroker-log-begin =============="
          docker logs rmqbroker
          echo "============== rmqbroker-log-end =============="

      - name: Stop RocketMQ
        if: always()
        run: docker-compose -f .ci/rocketmq.yml down
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ct-logs-${{matrix.os}}-${{matrix.otp_version}}
          path: _build/test/logs
